# Generated by Django 4.2.17 on 2025-04-05 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0002_alter_order_name_alter_orderdetail_name'),
        ('course', '0005_alter_activity_name_alter_course_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('discount', models.SmallIntegerField(choices=[(1, '减免'), (2, '折扣')], default=1, verbose_name='优惠方式')),
                ('coupon_type', models.SmallIntegerField(choices=[(0, '通用类型'), (1, '指定方向'), (2, '指定分类'), (3, '指定课程')], default=0, verbose_name='优惠券类型')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='启用时间')),
                ('end_time', models.DateTimeField(verbose_name='过期时间')),
                ('threshold', models.IntegerField(blank=True, default=0, verbose_name='优惠价格门槛')),
                ('calculation', models.CharField(help_text='\n            *号开头表示折扣价，例如*0.82表示八二折；<br>\n            -号开头表示减免价,例如-10表示在总价基础上减免10元<br>   \n            ', max_length=200, verbose_name='优惠公式')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
                'db_table': 'lf_coupon',
            },
        ),
        migrations.CreateModel(
            name='CouponLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0, verbose_name='优惠券状态')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_order', to='coupon.coupon', verbose_name='优惠券')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_coupon', to='order.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coupon_log', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '优惠券发放与使用记录',
                'verbose_name_plural': '优惠券发放与使用记录',
                'db_table': 'lf_coupon_log',
            },
        ),
        migrations.CreateModel(
            name='CouponCourseDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_direction', to='coupon.coupon', verbose_name='适用优惠券')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_coupon', to='course.coursedirection', verbose_name='适用课程方向')),
            ],
            options={
                'verbose_name': '优惠券与课程方向',
                'verbose_name_plural': '优惠券与课程方向',
                'db_table': 'lf_coupon_direction',
            },
        ),
        migrations.CreateModel(
            name='CouponCourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_coupon', to='course.coursecategory', verbose_name='适用课程类别')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_category', to='coupon.coupon', verbose_name='适用优惠券')),
            ],
            options={
                'verbose_name': '优惠券与课程类别',
                'verbose_name_plural': '优惠券与课程类别',
                'db_table': 'lf_coupon_category',
            },
        ),
        migrations.CreateModel(
            name='CouponCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_course', to='coupon.coupon', verbose_name='适用优惠券')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_coupon', to='course.course', verbose_name='适用课程')),
            ],
            options={
                'verbose_name': '优惠券与课程',
                'verbose_name_plural': '优惠券与课程',
                'db_table': 'lf_coupon_course',
            },
        ),
    ]
