# Generated by Django 4.2.17 on 2025-04-05 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_name_alter_orderdetail_name'),
        ('coupon', '0002_coupon_left_coupon_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='left',
            field=models.IntegerField(blank=True, default=50, verbose_name='剩余数量'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='启用时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='total',
            field=models.IntegerField(blank=True, default=50, verbose_name='发放数量'),
        ),
        migrations.AlterField(
            model_name='couponlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_coupon', to='order.order', verbose_name='订单'),
        ),
    ]
