# Generated by Django 4.2.17 on 2025-04-05 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_alter_coupon_left_alter_coupon_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='start_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='启用时间'),
        ),
        migrations.AlterField(
            model_name='couponlog',
            name='coupon',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_order', to='coupon.coupon', verbose_name='优惠券'),
        ),
    ]
