# Generated by Django 4.2.17 on 2025-04-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_alter_coupon_end_time_alter_coupon_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='calculation',
            field=models.CharField(help_text='\n            *号开头表示折扣价，例如*0.82表示八二折；<br>\n            -号开头表示减免价,例如-10表示在总价基础上减免10元<br>\n            ', max_length=200, verbose_name='优惠公式'),
        ),
    ]
