# Generated by Django 4.2.17 on 2025-04-06 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_credit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credit',
            name='remark',
        ),
        migrations.AlterModelTable(
            name='credit',
            table='lf_credit',
        ),
    ]
