# Generated by Django 4.2.17 on 2025-04-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_credit_remark_alter_credit_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='number',
            field=models.IntegerField(default=0, help_text='扣除积分需要设置为负数<br>添加积分需要设置为正数', verbose_name='积分数量'),
        ),
    ]
