# Generated by Django 4.2.17 on 2025-04-08 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_activity_name_alter_course_name_and_more'),
        ('user', '0004_alter_credit_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名称')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('study_time', models.IntegerField(default=0, verbose_name='学习时长')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_users', to='course.course', verbose_name='课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
