# Generated by Django 4.2.17 on 2025-04-08 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_usercourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercourse',
            options={'verbose_name': '用户课程关系表', 'verbose_name_plural': '用户课程关系表'},
        ),
        migrations.AlterModelTable(
            name='usercourse',
            table='lf_user_course',
        ),
    ]
