# Generated by Django 4.2.17 on 2025-04-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_usercourse_options_alter_usercourse_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女'), (3, '扶他')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='', max_length=200, verbose_name='职业'),
        ),
    ]
