# Generated by Django 4.2.17 on 2025-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
    ]
