# Generated by Django 4.2.17 on 2025-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_name_alter_orderdetail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='使用积分'),
        ),
    ]
