# Generated by Django 4.2.17 on 2025-04-02 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_credits_alter_course_course_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(auto_now=True, verbose_name='结束时间')),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注信息')),
                ('description', models.CharField(default='', max_length=200, verbose_name='活动介绍')),
            ],
            options={
                'verbose_name': '促销活动',
                'verbose_name_plural': '促销活动',
                'db_table': 'lf_activity',
            },
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('remark', models.CharField(default='', max_length=200, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '折扣类型',
                'verbose_name_plural': '折扣类型',
                'db_table': 'lf_discount_type',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('threshold', models.IntegerField(default=0, verbose_name='优惠门槛')),
                ('calculation', models.CharField(default='', max_length=200, verbose_name='折扣公式')),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.discounttype', verbose_name='折扣类型')),
            ],
            options={
                'verbose_name': '折扣',
                'verbose_name_plural': '折扣',
                'db_table': 'lf_discount',
            },
        ),
        migrations.CreateModel(
            name='CourseActivityDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.activity', verbose_name='活动')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course', verbose_name='课程')),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.discount', verbose_name='折扣')),
            ],
            options={
                'verbose_name': '课程参与活动折扣',
                'verbose_name_plural': '课程参与活动折扣',
                'db_table': 'lf_course_activity_discount',
            },
        ),
    ]
