# Generated by Django 4.2.17 on 2025-04-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_activity_discounttype_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(default=0, verbose_name='课程原价'),
        ),
    ]
