# Generated by Django 4.2.17 on 2025-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='courseactivitydiscount',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='discounttype',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
    ]
