# Generated by Django 4.2.17 on 2025-03-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(default='', max_length=200, verbose_name='链接')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否是外部链接')),
                ('position', models.IntegerField(choices=[(0, '顶部'), (1, '底部')], default=0, verbose_name='导航位置')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
