# Generated by Django 4.2.17 on 2025-03-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nav',
            options={'verbose_name': '导航菜单', 'verbose_name_plural': '导航菜单'},
        ),
        migrations.AlterModelTable(
            name='nav',
            table='lf_nav',
        ),
    ]
