# Generated by Django 4.2.17 on 2025-03-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_nav_options_alter_nav_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='名字')),
                ('order', models.IntegerField(default=0, verbose_name='序号')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否使用')),
                ('is_display', models.BooleanField(default=True, verbose_name='是否显示')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banner/%Y/', verbose_name='轮播图片')),
                ('link', models.CharField(default='', max_length=200, verbose_name='链接地址')),
                ('is_http', models.BooleanField(default=False, verbose_name='是否是外部链接')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'lf_banner',
            },
        ),
    ]
