# Generated by Django 4.2.17 on 2025-04-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='nav',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名称'),
        ),
    ]
